---
- hosts: all

  vars:
    home: "{{ lookup('env', 'HOME') }}"

  tasks:
    - name: Create ~/code Directory
      file:
        path: "{{ home }}/code"
        state: directory
        mode: "750"

    - name: Clone container-related git repos
      ansible.builtin.git:
        repo: "{{ item }}"
        dest: '{{ home }}/code/{{ item | urlsplit("path") }}'
        depth: 1
      tags: containers
      loop: "{{ lookup('file', 'git-repos.txt').splitlines() }}"

    - name: Install systemd-container
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - systemd-container
      become: true
      when: ansible_os_family == 'Debian'

    - name: Install build dependencies for runc
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - golang
        - libseccomp2
        - libseccomp-dev
      become: true
      when: ansible_os_family == 'Debian'

    - name: Install build dependencies for crun
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - make
        - git
        - gcc
        - build-essential
        - pkgconf
        - libtool
        - libprotobuf-c-dev
        - libcap-dev
        - libseccomp-dev
        - libyajl-dev
        - go-md2man
        - autoconf
        - python3
        - automake
      become: true
      when: ansible_os_family == 'Debian'

    - name: Install build dependencies for skopeo
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - libdevmapper-dev
        - libgpgme-dev
        - go-md2man
      become: true
      when: ansible_os_family == 'Debian'

    - name: Install build dependencies for youki
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - pkg-config
        - libsystemd-dev
        - libdbus-glib-1-dev
        - build-essential
        - libelf-dev
        - libseccomp-dev
      become: true
      when: ansible_os_family == 'Debian'

    - name: Install build dependencies for containerd
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - libbtrfs-dev
        - btrfs-progs
      become: true
      when: ansible_os_family == 'Debian'

    - name: Install build dependencies for conmon
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - gcc
        - git
        - libc6-dev
        - libglib2.0-dev
        - libseccomp-dev
        - pkg-config
        - make
      become: true
      when: ansible_os_family == 'Debian'

    - name: Install runtime dependencies for rootlesskit
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - uidmap
      become: true
      when: ansible_os_family == 'Debian'

    - name: Build runc
      community.general.make:
        chdir: "{{ home }}/code/fwilhe-containers/runc"

    - name: Install runc
      become: true
      community.general.make:
        chdir: "{{ home }}/code/fwilhe-containers/runc"
        target: install

    - name: configue crun
      ansible.builtin.shell: ./autogen.sh && ./configure
      args:
        chdir: "{{ home }}/code/fwilhe-containers/crun"

    - name: Build crun
      community.general.make:
        chdir: "{{ home }}/code/fwilhe-containers/crun"

    - name: Install crun
      become: true
      community.general.make:
        chdir: "{{ home }}/code/fwilhe-containers/crun"
        target: install

    - name: Build containerd
      community.general.make:
        chdir: "{{ home }}/code/fwilhe-containers/containerd"

    - name: Build CNI plugins
      ansible.builtin.shell: ./build_linux.sh
      args:
        chdir: "{{ home }}/code/fwilhe-containers/plugins"

    - name: Create /usr/local/libexec/cni Directory
      become: true
      file:
        path: /usr/local/libexec/cni
        state: directory
        mode: "777"

    - name: Install CNI plugins
      become: true
      ansible.builtin.shell: cp bin/* /usr/local/libexec/cni
      args:
        chdir: "{{ home }}/code/fwilhe-containers/plugins"

    - name: Install containerd
      become: true
      community.general.make:
        chdir: "{{ home }}/code/fwilhe-containers/containerd"
        target: install

    # - name: Build docker cli
    #   community.general.make:
    #     chdir: ~/code/docker/cli
    #     target: binary

    - name: Build skopeo
      community.general.make:
        chdir: "{{ home }}/code/fwilhe-containers/skopeo"

    - name: Install skopeo
      become: true
      community.general.make:
        chdir: "{{ home }}/code/fwilhe-containers/skopeo"
        target: install

    - name: Download bazel to build gvisor
      become: true
      get_url:
        url: https://releases.bazel.build/5.0.0/release/bazel-5.0.0-linux-x86_64
        dest: /usr/local/bin/bazel
        mode: "0777"

    - name: Build gvisor
      ansible.builtin.shell:
        cmd: bazel build -c opt //debian:debian
        chdir: "{{ home }}/code/fwilhe-containers/gvisor"

    - name: install the runsc binary
      become: true
      ansible.builtin.apt:
        deb: "{{ home }}/code/fwilhe-containers/gvisor/bazel-bin/debian/debian.deb"

    - name: Build cri-o
      community.general.make:
        chdir: "{{ home }}/code/fwilhe-containers/cri-o"

    - name: Install cri-o
      become: true
      community.general.make:
        chdir: "{{ home }}/code/fwilhe-containers/cri-o"
        target: install

    - name: Build conmon
      community.general.make:
        chdir: "{{ home }}/code/fwilhe-containers/conmon"

    - name: Install conmon
      become: true
      community.general.make:
        chdir: "{{ home }}/code/fwilhe-containers/conmon"
        target: install

    - name: Build rootlesskit
      community.general.make:
        chdir: "{{ home }}/code/fwilhe-containers/rootlesskit"

    - name: Install rootlesskit
      become: true
      community.general.make:
        chdir: "{{ home }}/code/fwilhe-containers/rootlesskit"
        target: install

    - name: Install build dependencies for slirp4netns
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - libglib2.0-dev
        - libslirp-dev
        - libcap-dev
        - libseccomp-dev
      become: true
      when: ansible_os_family == 'Debian'

    - name: configue slirp4netns
      ansible.builtin.shell: ./autogen.sh && ./configure --prefix=/usr
      args:
        chdir: "{{ home }}/code/fwilhe-containers/slirp4netns"

    - name: Build slirp4netns for rootless networking in podman
      community.general.make:
        chdir: "{{ home }}/code/fwilhe-containers/slirp4netns"

    - name: Install slirp4netns
      become: true
      community.general.make:
        chdir: "{{ home }}/code/fwilhe-containers/slirp4netns"
        target: install

    - name: Build podman
      community.general.make:
        chdir: "{{ home }}/code/fwilhe-containers/podman"

    - name: Install podman
      become: true
      community.general.make:
        chdir: "{{ home }}/code/fwilhe-containers/podman"
        target: install
