---
- hosts: all

  vars:
    home: "{{ lookup('env', 'HOME') }}"

  tasks:
    - name: Clone container-related git repos
      ansible.builtin.git:
        repo: "https://github.com/fwilhe-containers/code"
        dest: '{{ home }}/code/'
        recursive: true
      tags: containers

    - name: Install build dependencies for runc
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - golang
        - libseccomp2
        - libseccomp-dev
      become: true
      when: ansible_os_family == 'Debian'

    - name: Install build dependencies for crun
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - make
        - git
        - gcc
        - build-essential
        - pkgconf
        - libtool
        - libsystemd-dev
        - libprotobuf-c-dev
        - libcap-dev
        - libseccomp-dev
        - libyajl-dev
        - go-md2man
        - autoconf
        - python3
        - automake
      become: true
      when: ansible_os_family == 'Debian'

    - name: Build container-image
      community.general.make:
        chdir: "{{ home }}/code/container-image"

    - name: Install build dependencies for skopeo
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - libdevmapper-dev
        - libgpgme-dev
        - go-md2man
      become: true
      when: ansible_os_family == 'Debian'

    - name: Install build dependencies for youki
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - pkg-config
        - libsystemd-dev
        - libdbus-glib-1-dev
        - build-essential
        - libelf-dev
        - libseccomp-dev
      become: true
      when: ansible_os_family == 'Debian'

    - name: Install build dependencies for containerd
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - libbtrfs-dev
        - btrfs-progs
      become: true
      when: ansible_os_family == 'Debian'

    - name: Install build dependencies for conmon
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - gcc
        - git
        - libc6-dev
        - libglib2.0-dev
        - libseccomp-dev
        - pkg-config
        - make
      become: true
      when: ansible_os_family == 'Debian'

    - name: Install runtime dependencies for rootlesskit
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - uidmap
      become: true
      when: ansible_os_family == 'Debian'

    - name: Build runc
      community.general.make:
        chdir: "{{ home }}/code/runc"

    - name: Install runc
      become: true
      community.general.make:
        chdir: "{{ home }}/code/runc"
        target: install

    - name: configue crun
      ansible.builtin.shell: ./autogen.sh && ./configure
      args:
        chdir: "{{ home }}/code/crun"

    - name: Build crun
      community.general.make:
        chdir: "{{ home }}/code/crun"

    - name: Install crun
      become: true
      community.general.make:
        chdir: "{{ home }}/code/crun"
        target: install

    - name: configue bubblewrap
      ansible.builtin.shell: ./autogen.sh
      args:
        chdir: "{{ home }}/code/bubblewrap"

    - name: Build bubblewrap
      community.general.make:
        chdir: "{{ home }}/code/bubblewrap"

    - name: Install bubblewrap
      become: true
      community.general.make:
        chdir: "{{ home }}/code/bubblewrap"
        target: install

    - name: Build ignite
      community.general.make:
        chdir: "{{ home }}/code/ignite"
        target: ignite
        params:
          GO_MAKE_TARGET: local

    - name: Install ignite
      community.general.make:
        chdir: "{{ home }}/code/ignite"
        target: install
        params:
          GO_MAKE_TARGET: local

    - name: Build containerd
      community.general.make:
        chdir: "{{ home }}/code/containerd"

    - name: Build CNI plugins
      ansible.builtin.shell: ./build_linux.sh
      args:
        chdir: "{{ home }}/code/plugins"

    - name: Create /usr/local/libexec/cni Directory
      become: true
      file:
        path: /usr/local/libexec/cni
        state: directory
        mode: "777"

    - name: Install CNI plugins
      become: true
      ansible.builtin.shell: cp bin/* /usr/local/libexec/cni
      args:
        chdir: "{{ home }}/code/plugins"

    - name: Install containerd
      become: true
      community.general.make:
        chdir: "{{ home }}/code/containerd"
        target: install

    - name: Build skopeo
      community.general.make:
        chdir: "{{ home }}/code/skopeo"

    - name: Install skopeo
      become: true
      community.general.make:
        chdir: "{{ home }}/code/skopeo"
        target: install

    - name: Build cri-o
      community.general.make:
        chdir: "{{ home }}/code/cri-o"

    - name: Install cri-o
      become: true
      community.general.make:
        chdir: "{{ home }}/code/cri-o"
        target: install

    - name: Build conmon
      community.general.make:
        chdir: "{{ home }}/code/conmon"

    - name: Install conmon
      become: true
      community.general.make:
        chdir: "{{ home }}/code/conmon"
        target: install

    - name: Build rootlesskit
      community.general.make:
        chdir: "{{ home }}/code/rootlesskit"

    - name: Install rootlesskit
      become: true
      community.general.make:
        chdir: "{{ home }}/code/rootlesskit"
        target: install

    - name: Install build dependencies for slirp4netns
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - libglib2.0-dev
        - libslirp-dev
        - libcap-dev
        - libseccomp-dev
      become: true
      when: ansible_os_family == 'Debian'

    - name: configue slirp4netns
      ansible.builtin.shell: ./autogen.sh && ./configure --prefix=/usr
      args:
        chdir: "{{ home }}/code/slirp4netns"

    - name: Build slirp4netns for rootless networking in podman
      community.general.make:
        chdir: "{{ home }}/code/slirp4netns"

    - name: Install slirp4netns
      become: true
      community.general.make:
        chdir: "{{ home }}/code/slirp4netns"
        target: install

    - name: Build ctop
      community.general.make:
        chdir: "{{ home }}/code/ctop"
        target: build

    - name: Build ctop
      become: true
      ansible.builtin.shell:
        cmd: cp ctop /usr/local/bin
        chdir: "{{ home }}/code/ctop"

    - name: Build podman
      community.general.make:
        chdir: "{{ home }}/code/podman"

    - name: Install podman
      become: true
      community.general.make:
        chdir: "{{ home }}/code/podman"
        target: install
