# based on https://github.com/ruzickap/ansible-my_workstation/blob/main/.github/workflows/fedora.yml

name: CI in Virtualbox (slow)
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VAGRANT_DEFAULT_PROVIDER: virtualbox

jobs:
  virtualbox:
    runs-on: macos-10.15
    timeout-minutes: 100
    steps:
      - uses: actions/checkout@v3

      - name: Install brew packages
        run: |
          rm /usr/local/bin/2to3
          brew install ansible gnu-sed hudochenkov/sshpass/sshpass vagrant

      - name: Start VM, run demo playbook
        run: |
          vagrant up || ( vagrant destroy --force && vagrant up )

      - name: Stop VM
        run: |
          vagrant halt

      - name: Package VM
        run: |
          vagrant package --machine-readable --output containers-lab.box

      - run: ls -la