# based on https://github.com/ruzickap/ansible-my_workstation/blob/main/.github/workflows/fedora.yml

name: CI in Virtualbox (slow)
on:
  push:
    branches:
      - main
    paths:
      - Vagrantfile
      - .github/workflows/ci-vm.yml
      - .playbook.yaml
      - git-repos.txt
  workflow_dispatch:

env:
  VAGRANT_DEFAULT_PROVIDER: virtualbox

jobs:
  virtualbox:
    runs-on: macos-10.15
    timeout-minutes: 100
    steps:
      - uses: actions/checkout@v3

      - name: Install brew packages
        run: |
          brew install ansible vagrant

      - name: Start VM to build tools from source
        run: |
          vagrant up || ( vagrant destroy --force && vagrant up )

      - name: Check version of built tools
        run: vagrant ssh --command "bash versions.sh"

      - name: Check basic podman functionality
        run: vagrant ssh --command "bash podman.sh"

      - name: Check basic skopeo functionality
        run: vagrant ssh --command "bash skopeo.sh"

      - name: Package VM
        run: |
          vagrant package --debug --no-tty --output containers-lab.box --info info.json
      - run: ls -la

      - uses: actions/upload-artifact@v3
        with:
          name: containers-lab-vagrant-box
          path: containers-lab.box
