# based on https://github.com/ruzickap/ansible-my_workstation/blob/main/.github/workflows/fedora.yml

name: CI in Virtualbox (slow)
on:
  push:
    branches:
      - main
    paths:
      - Vagrantfile
      - .github/workflows/ci-vm.yml
      - .playbook.yaml
      - git-repos.txt
  workflow_dispatch:

env:
  VAGRANT_DEFAULT_PROVIDER: virtualbox

jobs:
  virtualbox:
    runs-on: macos-10.15
    timeout-minutes: 100
    steps:
      - uses: actions/checkout@v3

      - name: Install brew packages
        run: |
          brew install ansible vagrant

      - name: Start VirtualBox VM
        run: |
          vagrant up || ( vagrant destroy --force && vagrant up )
