name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Hello World
      run: |
        docker run hello-world
    - name: Hello World
      run: |
        ansible-playbook --inventory "localhost," --connection=local playbook.yaml
