name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:21.10
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yqq ansible git python3-apt build-essential
      - name: Run demo playbook
        run: ansible-playbook -vvv --inventory "localhost," --connection=local playbook.yaml
      - run: runc --version
      - run: containerd --version
      - run: skopeo --version
      - run: crun --version
      - run: podman --version
      - run: crio --version
      - run: find ~/code/fwilhe-containers/container-image