name: CI in Docker (fast, no full system-access)
on:
  push:
  workflow_dispatch:

env:
  ANSIBLE_STDOUT_CALLBACK: yaml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:21.10
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yqq ansible git python3-apt build-essential
      - name: Run demo playbook
        run: ansible-playbook -v --inventory "localhost," --connection=local playbook.yaml
      - run: conmon --version
      - run: containerd --version
      - run: crio --version
      - run: crun --version
      - run: podman --version
      - run: rootlesskit --version
      - run: runc --version
      - run: runsc --version
      - run: skopeo --version
