name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:21.10
    steps:
    - uses: actions/checkout@v2
    - name: Run demo playbook
      run: |
        ansible-playbook --inventory "localhost," --connection=local playbook.yaml
