name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Hello World (docker)
      run: |
        docker run hello-world

    - name: Hello World (podman)
      run: |
        podman run hello-world

    - name: Install ansible
      run: sudo pip3 install ansible

    - name: Run containers demo playbook
      run: ansible-playbook -v playbook.yaml
